# Generated by Django 3.1 on 2023-04-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeName', models.CharField(blank=True, default='Актив 1', max_length=255, null=True, verbose_name='Название актива')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('cash', models.FloatField(blank=True, null=True, verbose_name='Наличные средства')),
                ('accountsReceivable', models.FloatField(blank=True, default=0, null=True, verbose_name='Дебиторская задолженность')),
                ('inventory', models.FloatField(blank=True, default=0, null=True, verbose_name='Инвентаризация')),
                ('prepaidExpenses', models.FloatField(blank=True, default=0, null=True, verbose_name='Предоплаченные расходы')),
                ('shortTermInvestments', models.FloatField(blank=True, default=0, null=True, verbose_name='Краткосрочные инвестиции')),
                ('longTermInvestments', models.FloatField(blank=True, default=0, null=True, verbose_name='Долгосрочные инвестиции')),
                ('propertyPlantEquipement', models.FloatField(blank=True, default=0, null=True, verbose_name='Основные средства')),
                ('lessAccumulatedDepreciation', models.FloatField(blank=True, default=0, null=True, verbose_name='За вычетом накопленной амортизации')),
                ('intangibleAssets', models.FloatField(blank=True, default=0, null=True, verbose_name='Нематериальные активы')),
                ('deferredIncomeTax', models.FloatField(blank=True, default=0, null=True, verbose_name='Отложенный налог на прибыль')),
                ('other', models.FloatField(blank=True, default=0, null=True, verbose_name='Разное')),
                ('accountsPayable', models.FloatField(blank=True, null=True, verbose_name='Кредиторская задолженность')),
                ('shortTermLoans', models.FloatField(blank=True, null=True, verbose_name='Краткосрочные кредиты')),
                ('incomeTaxes', models.FloatField(blank=True, null=True, verbose_name='Подлежащий уплате подоходный налог')),
                ('accruedSalaries', models.FloatField(blank=True, null=True, verbose_name='Начисленная заработная плата')),
                ('unearnedRevenue', models.FloatField(blank=True, null=True, verbose_name='Незаработанный доход')),
                ('currentPortion', models.FloatField(blank=True, null=True, verbose_name='Текущая часть долгосрочного долга')),
                ('longTermDebt', models.FloatField(blank=True, null=True, verbose_name='Наличные средства')),
                ('defferedIncomeTax', models.FloatField(blank=True, null=True, verbose_name='Наличные средства')),
                ('otherLongTerm', models.FloatField(blank=True, null=True, verbose_name='Наличные средства')),
                ('ownerInvestment', models.FloatField(blank=True, null=True, verbose_name='Наличные средства')),
                ('retainedEarnings', models.FloatField(blank=True, null=True, verbose_name='Наличные средства')),
                ('otherOwnerInvestment', models.FloatField(blank=True, null=True, verbose_name='Наличные средства')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='financeApp.company', verbose_name='Компания')),
            ],
        ),
    ]
